<?php
/**
 * @file
 * This is a the install for the penton_full_gallery module.
 *
 * This install file should be used for any installs or updates needed for
 * penton_full_gallery.
 */

/**
 * Update aliases.
 */
function penton_full_gallery_update_7000() {
  _penton_full_gallery_update_aliases();
}

/**
 * Update aliases.
 */
function penton_full_gallery_update_7001() {
  _penton_full_gallery_update_aliases();
}
