<?php
/**
 * @file
 * This is an extender module for googlesitemap.
 *
 * This module provides a query alter for the googlesitemap contrib module.
 */

/**
 * Implements hook_query_TAG_alter().
 */
function penton_googlesitemap_query_googlenews_sitemap_alter(QueryAlterableInterface $query) {
  $query->leftJoin(
    'field_data_field_penton_article_type',
    'at',
    '(at.entity_id=n.nid)');
  $query->leftJoin(
    'taxonomy_term_data',
    'ttd',
    '(ttd.tid=at.field_penton_article_type_tid)');
  $query->leftJoin(
    'field_data_field_penton_google_news_flag',
    'gn',
    '(gn.entity_id=n.nid)');
  $query->leftJoin(
    'field_data_field_penton_press_release_flag',
    'pr',
    '(pr.entity_id=n.nid)');
  $query->leftJoin(
    'field_data_field_penton_aggregated_content',
    'ac',
    '(ac.entity_id=n.nid)');
  $query->leftJoin(
    'field_data_field_penton_native_advertising',
    'na',
    '(na.entity_id=n.nid)');
  $query->condition('ttd.name', 'Article', '=');
  $query->condition('gn.field_penton_google_news_flag_value', '1', '=');
  $query->condition('pr.field_penton_press_release_flag_value', '0', '=');
  $query->condition('ac.field_penton_aggregated_content_value', '0', '=');
  $query->condition('na.field_penton_native_advertising_value', '0', '=');
}

/**
 * Implements hook_node_submit().
 */
function penton_googlesitemap_node_submit($node, $form, &$form_state) {
  _penton_googlesitemap_clear_cache($node);
}

/**
 * Implements hook_node_update().
 */
function penton_googlesitemap_node_update($node) {
  _penton_googlesitemap_clear_cache($node);
}

/**
 * Clear the Google sitemap cache.
 *
 * @author James Linnell james.linnell@ixxus.com
 *
 * @param object $node
 *   The node object.
 */
function _penton_googlesitemap_clear_cache($node) {
  if ($node->type == 'article') {
    if (isset($node->field_penton_article_type['und'][0]) && $node->field_penton_article_type['und'][0]['name'] == 'Article') {
      if ($node->field_penton_google_news_flag['und'][0]['value'] == 1) {
        if ($node->field_penton_press_release_flag['und'][0]['value'] != 1 || $node->field_penton_aggregated_content['und'][0]['value'] != 1 || $node->field_penton_native_advertising['und'][0]['value'] != 1) {
          // Then clear the cache.
          cache_clear_all('googlenews', 'cache', TRUE);
        }
      }
    }
  }
}
