<?php
/**
 * @file
 * Penton Blocks module core file.
 */

/**
 * Implements hook_block_info().
 */
function penton_blocks_block_info() {
  $blocks = array();
  $blocks['penton_top_stories_main'] = array(
    'info' => t('Penton Homepage Top Stories main block'),
    'cache' => DRUPAL_NO_CACHE,
  );
  $blocks['penton_top_stories_right'] = array(
    'info' => t('Penton Homepage Top Stories block in right rail'),
    'cache' => DRUPAL_NO_CACHE,
  );
  $blocks['penton_usermarketing_promo'] = array(
    'info' => t('Penton Usermarketing promo block'),
    'cache' => DRUPAL_NO_CACHE,
  );
  $blocks['penton_featured_categories'] = array(
    'info' => t('Penton Homepage Featured Categories block'),
    'cache' => DRUPAL_NO_CACHE,
  );
  $blocks['penton_featured_program'] = array(
    'info' => t('Penton Homepage Featured Program block'),
    'cache' => DRUPAL_NO_CACHE,
  );
  $blocks['penton_featured_media'] = array(
    'info' => t('Penton Homepage Featured Media block'),
    'cache' => DRUPAL_NO_CACHE,
  );
  $blocks['penton_sidebar_recent'] = array(
    'info' => t('Sidebar Recent'),
    'cache' => DRUPAL_NO_CACHE,
  );
  $blocks['penton_newsletter_signup'] = array(
    'info' => t('Inline Newsletter Sign-Up block'),
    'cache' => DRUPAL_NO_CACHE,
  );
  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function penton_blocks_block_view($delta = '') {
  $block = array();
  switch ($delta) {
    case 'penton_top_stories_main':
      $block['subject'] = t('Top Stories');
      $block['content'] = array('penton_top_stories_main' => array());
      $block = $block + _penton_blocks_top_main_block_content();
      break;

    case 'penton_top_stories_right':
      $block['subject'] = t('Top Stories second');
      $block['content'] = array('penton_top_stories_right' => array());
      $block = $block + _penton_blocks_top_second_block_content();
      break;

    case 'penton_usermarketing_promo':
      $block['subject'] = t('Usermarketing promo');
      $block['content'] = array('penton_usermarketing_promo' => array());
      $block = $block + _penton_blocks_usermarketing_promo_block_content();
      break;

    case 'penton_featured_categories':
      $block['subject'] = 'Featured Categories';
      $block['content'] = array('penton_featured_categories' => array());
      $block = $block + _penton_blocks_categories_block_content();
      break;

    case 'penton_featured_program':
      $block['subject'] = t('Featured Program');
      $block['content'] = array('penton_featured_program' => array());
      $block = $block + _penton_blocks_program_block_content();
      break;

    case 'penton_featured_media':
      $block['subject'] = t('Featured Media');
      $block['content'] = array('penton_featured_media' => array());
      $block = $block + _penton_blocks_featured_media_block_content();
      break;

    case 'penton_sidebar_recent':
      $block['subject'] = t('Recent');
      $block['content'] = array('penton_featured_content' => array());
      $block = $block + _penton_blocks_sidebar_recent_block_content();
      break;

    case 'penton_newsletter_signup':
      $block['subject'] = '';
      $block['content'] = array('penton_newsletter_signup' => array());
      $block = $block + _penton_blocks_newsletter_signup();
      break;
  }
  return $block;
}

/**
 * Compose variables.
 * @return array
 *   Returning variables array to use in template.
 */
function _penton_blocks_program_block_content() {
  $data = penton_homepage_display_get_full_data();

  return array('program' => $data['featured_program']);
}

/**
 * Compose variables.
 * @return array
 *   Returning variables array to use in template.
 */
function _penton_blocks_top_main_block_content() {
  $data = penton_homepage_display_get_full_data();

  return array('articles' => array_slice($data['top_stories'], 0, 3));
}

/**
 * Compose variables.
 * @return array
 *   Returning variables array to use in template.
 */
function _penton_blocks_top_second_block_content() {
  $data = penton_homepage_display_get_full_data();

  return array(
    'articles' => array_slice($data['top_stories'], 3),
    'pillar' => !empty($data['pillar_promo1']) ? $data['pillar_promo1'] : array(),
  );
}

/**
 * Compose variables.
 * @return array
 *   Returning variables array to use in template.
 */
function _penton_blocks_usermarketing_promo_block_content() {
  $term = menu_get_object('taxonomy_term', 2);
  $custom_vocabularies = array(
    'program',
    'categories',
  );

  $result = array();
  if (!empty($term) && in_array($term->vocabulary_machine_name, $custom_vocabularies)) {
    $result['on_term_page'] = TRUE;
  }

  if (!empty($result['on_term_page']) && !empty($term->field_penton_user_marketing_pro[LANGUAGE_NONE][0]['target_id'])) {
    $result['promo'] = node_load($term->field_penton_user_marketing_pro[LANGUAGE_NONE][0]['target_id']);
  }
  else {
    $data = penton_homepage_display_get_full_data();
    $result['promo'] = $data['usermarketing_promo'];
  }

  return $result;
}

/**
 * Compose variables.
 * @return array
 *   Returning variables array to use in template.
 */
function _penton_blocks_sidebar_recent_block_content() {
  $data = penton_homepage_display_get_full_data();
  return array(
    'pillar' => !empty($data['pillar_promo2']) ? $data['pillar_promo2'] : array(),
    'featured_nodes' => !empty($data['sidebar_featured_nodes']) ? $data['sidebar_featured_nodes'] : array(),
    'recent_nodes' => !empty($data['sidebar_recent_nodes']) ? $data['sidebar_recent_nodes'] : array(),
  );
}

/**
 * Compose variables.
 * @return array
 *   Returning variables array to use in template.
 */
function _penton_blocks_featured_media_block_content() {
  $data = penton_homepage_display_get_full_data();

  return array('article' => !empty($data['featured_media_node'][0]) ? $data['featured_media_node'][0] : array());
}


/**
 * Compose variables.
 * @return array
 *   Returning variables array to use in template.
 */
function _penton_blocks_categories_block_content() {
  $data = penton_homepage_display_get_full_data();

  return array('categories' => !empty($data['featured_categories']) ? $data['featured_categories'] : array());
}

/**
 * Compose variables.
 * @return array
 *   Returning variables array to use in template.
 */
function _penton_blocks_newsletter_signup() {
  $arr = array();

  if (!empty($_COOKIE['Drupal_visitor_nlsub'])) {
    $cookie = $_COOKIE['Drupal_visitor_nlsub'];
    $arr['thank_you'] = TRUE;
    user_cookie_save(array('nlsub' => ''));
    $_COOKIE['Drupal_visitor_nlsub'] = '';

    if (!empty($_COOKIE['Drupal_visitor_subemail'])) {
      user_cookie_save(array('subemail' => ''));
      $_COOKIE['Drupal_visitor_subemail'] = '';
    }

    if ($cookie == 'newsub') {
      global $user;
      $arr['new_user_name'] = $user->name;
    }
  }
  elseif (!user_is_logged_in()) {
    if (module_exists('penton_user_register')
      && module_exists('penton_newsletter_manager')
      && $promoted_title = penton_newsletter_manager_get_promoted_newsletter_title()
    ) {
      $form = drupal_get_form('penton_user_register_newsletter_signup_form');

      $arr['title'] = $promoted_title;
      $arr['form'] = $form;
    }
  }
  return $arr;
}
