<?php
/**
 * @file
 * Penton Rss module core file.
 */

/**
 * Defined vocabulary ids.
 */
define('PENTON_RSS_TERM_CATEGORY_VID', 2);
define('PENTON_RSS_TERM_PROGRAM_VID', 3);

/**
 * Implemets hook_menu().
 */
function penton_rss_menu() {

  $items['feed/%/rss.xml'] = array(
    'title' => 'RSS feed of latest article',
    'page callback' => 'get_rss_feeds',
    'page arguments' => array(1),
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
  );
  return $items;
}

/**
 * Menu callback.
 */
function get_rss_feeds($arg) {

  $term = end(taxonomy_get_term_by_name($arg));
  $query = new EntityFieldQuery();

  // Select article from the category or program.
  switch ($term->vid) {
    case PENTON_RSS_TERM_CATEGORY_VID:
      $collection = $query->entityCondition('entity_type', 'node')
        ->entityCondition('bundle', 'article')
        ->fieldCondition('field_penton_primary_category', 'tid', $term->tid, '=')
        ->fieldCondition('field_penton_allow_in_rss_feed', 'value', TRUE, '=')
        ->propertyCondition('status', NODE_PUBLISHED)
        ->fieldOrderBy('field_penton_published_datetime', 'value', 'DESC')
        ->execute();
      break;

    case PENTON_RSS_TERM_PROGRAM_VID:
      $collection = $query->entityCondition('entity_type', 'node')
        ->entityCondition('bundle', 'article')
        ->fieldCondition('field_penton_program', 'tid', $term->tid, '=')
        ->fieldCondition('field_penton_allow_in_rss_feed', 'value', TRUE, '=')
        ->propertyCondition('status', NODE_PUBLISHED)
        ->fieldOrderBy('field_penton_published_datetime', 'value', 'DESC')
        ->execute();
      break;

    default:
      $collection['node'] = array();
  }

  $feed_ids = array();
  foreach ($collection['node'] as $items) {
    $feed_ids[] = $items->nid;
  }
  node_feed($feed_ids);
}
