<?php
/**
 * @file
 * Penton content manager.
 */

/**
 * Define role id for role content manager.
 */
define('PENTON_CONTENT_PREVIEW_RID', 9);

/**
 * Implements hook_page_delivery_callback_alter().
 */
function penton_content_preview_page_delivery_callback_alter(&$callback) {
  if ($callback == 'drupal_deliver_html_page') {
    $callback = '_penton_content_preview_deliver_html_page';
  }
}

/**
 * Override the callback.
 *
 * @param pagecallback $page_callback_result
 *   The page callback.
 */
function _penton_content_preview_deliver_html_page($page_callback_result) {
  if (is_int($page_callback_result)) {
    if ($page_callback_result == MENU_ACCESS_DENIED) {
      if (user_is_anonymous()) {
        // User is not logged in so we must check to see if there is $_post to
        // log them in or not.
        global $_POST;
        if ($_POST) {
          if (_penton_content_preview_user_login($_POST) == TRUE) {
            $refer = explode(" ", variable_get('penton_alfresco_referer', 'alfdev.penton.ixxus.com'));
            $alf = FALSE;
            foreach ($refer as $item) {
              if (strpos($_SERVER['HTTP_REFERER'], $item) !== FALSE) {
                $alf = TRUE;
                break;
              }
            }
            if ($alf !== FALSE) {
              drupal_goto('node/' . $_POST['nid']);
            }
            else {
              drupal_deliver_html_page($page_callback_result);
            }
          }
          else {
            drupal_deliver_html_page($page_callback_result);
          }
        }
        else {
          drupal_deliver_html_page($page_callback_result);
        }
      }
      else {
        drupal_deliver_html_page($page_callback_result);
      }
    }
    else {
      drupal_deliver_html_page($page_callback_result);
    }
  }
  else {
    drupal_deliver_html_page($page_callback_result);
  }
}

/**
 * Log in a user with the POST attributes.
 *
 * @param array $post
 *   The post array.
 *
 * @return bool
 *   Return user login.
 */
function _penton_content_preview_user_login($post) {
  // TODO: @ixxus please refactor it. Check $_POST['username']
  // TODO: and $_POST['password'] on !empty() to prevent php notices.
  if ($post['username']) {
    if (user_authenticate($post['username'], $post['password'])) {
      $user_obj = user_load_by_name($post['username']);
      $form_state = array();
      $form_state['uid'] = $user_obj->uid;
      user_login_submit(array(), $form_state);
      return TRUE;
    }
    else {
      return FALSE;
    }
  }
  else {
    return FALSE;
  }
}
