<?php
/**
 * @file
 * This is an extender module for xmlsitemap.
 *
 * This module provides xmlsitemap hooks for xmlsitemap contrib module.
 */

/**
 * Implements hook_xmlsitemap_link_alter().
 */
function penton_xmlsitemap_xmlsitemap_link_alter(&$link, $context) {
  if ($link['type'] == 'node' && $link['subtype'] == 'article' && !empty($context['node'])) {
    if ($context['node']->status == NODE_PUBLISHED
      && empty($context['node']->field_penton_aggregated_content[LANGUAGE_NONE][0]['value'])
      && empty($context['node']->metatags[LANGUAGE_NONE]['robots']['value']['noindex'])) {
      $link['status'] = '1';
      $link['status_override'] = '1';
      $link['access'] = 1;
    }
    else {
      $link['status'] = '0';
      $link['status_override'] = '0';
      $link['access'] = 0;
    }
  }
  if ($link['type'] == 'user' && !empty($context['user'])) {
    if (user_has_role(PENTON_AUTHOR_RID, $context['user'])) {
      $link['status'] = '1';
      $link['status_override'] = '1';
      $link['access'] = 1;
    }
    else {
      $link['status'] = '0';
      $link['status_override'] = '0';
      $link['access'] = 0;
    }
  }
}
