<?php
/**
 * @file
 * Code for the Penton Mollom feature.
 */

include_once 'penton_mollom.features.inc';

/**
 * Implements hook_mollom_form_info_alter().
 */
function penton_mollom_mollom_form_info_alter(&$form_info, $form_id) {
  if ($form_id == 'user_profile_form') {
    $form_info['elements']['field_penton_profile][und][0][first_name'] = t('First name');
    $form_info['elements']['field_penton_profile][und][0][last_name'] = t('Last name');
    $form_info['elements']['field_penton_profile][und][0][organisation_name'] = t('Company');
  }
}
